taassignment/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from taassignment.users import views as users
from taassignment.courses import views as courses
from . import views

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', views.home , name='home'),

    url(r'^users/list$', users.list_, name='users-list'),
    url(r'^users/create$', users.create, name='users-create'),
    url(r'^users/edit/(?P<userid>\d+)$' , users.edit, name='users-edit'),
    url(r'^users/delete/(?P<userid>\d+)$', users.delete, name='users-delete'),
    url(r'^users/clear_tas$', users.clear_tas, name='users-clear-tas'),
    url(r'^users/clear_faculty$', users.clear_faculty, name='users-clear-faculty'),
    url(r'^users/upload/', users.upload, name='users-upload' ),

    url(r'^courses/list$', courses.list_, name='courses-list'),
    url(r'^courses/upload/',courses.upload, name='courses-upload' ),
    url(r'^courses/create$', courses.create, name='courses-create'),
    url(r'^courses/edit/(?P<courseid>\d+)$' , courses.edit, name='courses-edit'),
    url(r'^courses/delete/(?P<courseid>\d+)$', courses.delete, name='courses-delete'),
    url(r'^courses/clear$', courses.clear, name='courses-clear'),
    url(r'^courses/change_tas/$', courses.change_tas, name='courses-change-tas'),
    url(r'^courses/download/$', courses.csv_courses_download, name='courses-download'),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_CAS:
    urlpatterns += patterns('',
        url(r'^accounts/login/$', 'djangocas.views.login', name='account-login'),
        url(r'^accounts/logout/$', 'djangocas.views.logout', name='account-logout'),
    )
    

taassignment/course/models.py
from django.db import models
from taassignment.users.models import User 
# Create your models here.

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    course_no = models.CharField(max_length=10,blank=False)
    course_name = models.CharField(max_length=100, blank=False)
    faculties = models.ManyToManyField(User, related_name='faculties', blank=True)
    tas = models.ManyToManyField(User, related_name='tas', blank=True)

    class Meta:
        ordering = ('course_name',)
        permissions = (
            ("change_ta", "Can change TA in this course"),
        )

taassignment/course/forms.py
from django import forms
from taassignment.course.models import Course 
from taassignment.users.models import User 

class UploadFileForm(forms.Form):
    file  = forms.FileField()

class CourseForm(forms.ModelForm):
       
    course_no = forms.CharField(label="Course", required=True, widget=forms.TextInput(attrs={'placeholder': 'Course No.', 'class' : 'form-control'}))
    course_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Course Name', 'class' : 'form-control'}))
    
    list_of_faculties = User.objects.filter(is_faculty=True)
    list_of_tas = User.objects.filter(is_ta=True)

    faculties = forms.ModelMultipleChoiceField(label="Teacher", required=True, queryset=list_of_faculties)
    tas = forms.ModelMultipleChoiceField(label="TA", required=False, queryset=list_of_tas)

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
       
        self.fields['faculties'].widget.attrs['class'] = 'form-control'
        self.fields['tas'].widget.attrs['class'] = 'form-control'

    def clean_faculties(self):
        faculties = self.cleaned_data.get('faculties')
        
        return User.objects.filter(id__in=faculties)

    def clean_tas(self):
        tas = self.cleaned_data.get('tas')

        return User.objects.filter(id__in=tas)

    class Meta:
        model = Course
        fields = (
            'course_no',
            'course_name',
            'faculties',
            'tas'
        )

taassignment/courses/forms.py
from django import forms
from .models import Course
from taassignment.users.models import User

class UploadFileForm(forms.Form):
    file  = forms.FileField()


class CourseForm(forms.ModelForm):
       
    course_no = forms.CharField(label="Course", required=True, widget=forms.TextInput(attrs={'placeholder': 'Course No.', 'class' : 'form-control'}))
    section_no = forms.CharField(label="Section", required=False, widget=forms.TextInput(attrs={'placeholder': 'Section No.', 'class': 'form-control'}))
    course_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Course Name', 'class' : 'form-control'}))
    
    list_of_faculties = User.objects.filter(is_faculty=True)
    list_of_tas = User.objects.filter(is_ta=True)

    faculties = forms.ModelMultipleChoiceField(label="Teacher", required=True, queryset=list_of_faculties)
    max_tas = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'placeholder': "Max No. TA's", 'class': 'form-control'}))
    tas = forms.ModelMultipleChoiceField(label="TA's", required=False, queryset=list_of_tas)

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
       
        self.fields['faculties'].widget.attrs['class'] = 'form-control'
        self.fields['tas'].widget.attrs['class'] = 'form-control'

    def clean_faculties(self):
        faculties = self.cleaned_data.get('faculties')
        
        return User.objects.filter(id__in=faculties)

    def clean_tas(self):
        tas = self.cleaned_data.get('tas')
        max_tas = self.cleaned_data.get('max_tas')
        if tas.count() > max_tas:
            raise forms.ValidationError("Exceeds maximum allowed TA's")
        
        return User.objects.filter(id__in=tas)


    class Meta:
        model = Course
        fields = (
            'course_no',
            'section_no',
            'course_name',
            'faculties',
            'max_tas',
            'tas',

        )


class SelectionForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(SelectionForm, self).__init__(*args, **kwargs)

        self.courses = Course.objects.filter(faculties=self.user)
        tas = User.objects.filter(is_ta=True)
        for course in self.courses:
            field = forms.ModelMultipleChoiceField(queryset=tas, required=False, widget=forms.SelectMultiple(attrs={'class': 'multi_select form-control', 'data-max': course.max_tas }))
            field.initial = course.tas.all()
            self.fields[str(course.pk)] = field

    def clean(self):
        for course in self.courses:
            self.tas = self.cleaned_data.get(str(course.pk), [])
            if self.tas.count() > course.max_tas:
                raise forms.ValidationError("Exceeds maximum allowed TA's for course %s" % course)
            return User.objects.filter(id__in=self.tas) 

    def save(self):
        for course in self.courses:
            tas = self.tas
            course.tas.clear()
            for ta in tas:
                course.tas.add(ta)

taassignment/course/views.py
import os
from django.db import transaction
from datetime import datetime 
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.db import IntegrityError
from django.core.urlresolvers import reverse
from django.contrib import messages

from djangocas.decorators import user_passes_test
from taassignment.perm import faculty_member_check, admin_member_check, ta_member_check

from taassignment.course.models import Course 
from taassignment.users.models import User 
from .forms import CourseForm
from django.http import HttpResponseRedirect
from taassignment.course.models import Course
from taassignment.users.models import User
from taassignment.course.forms import UploadFileForm
from django.db.models import Count, Min
from django.conf import settings
from taassignment.users.forms import SelectionForm
import csv

import ldap
from django.conf import settings


# Upload Courses
@user_passes_test(admin_member_check, login_url="/accounts/login")
def upload_courses(request):
    error = None
    section = "course-home"

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if  form.is_valid():
            try:
                with transaction.atomic():
                    _request_csv_courses_upload(request, request.FILES['file'])
            except (TypeError, ValueError) :
                error='Wrong file type, number of columns do not mach!'
            except Exception as e:
                error= '%s (%s)' % (e.message, type(e))
            else:
                return HttpResponseRedirect(reverse("staff-home-courses"))
    else:
        form = UploadFileForm()
    return render(request,'admin/upload_courses_import.html', {
        'form': form, 
        'error': error,
        'section' : section,
    })


# Upload Tas
@user_passes_test(admin_member_check, login_url="/accounts/login")
def upload_tas(request):
    error = None
    section = 'user-home'

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if  form.is_valid():
            try:
                with transaction.atomic():
                    _request_csv_tas_upload(request, request.FILES['file'])
            except (TypeError, ValueError) :
                error='Wrong file type, number of columns do not mach!'
            except Exception as e:
                error= '%s (%s)' % (e.message, type(e))
            else:  
                return HttpResponseRedirect(reverse("staff-home-users"))
    else:
        form = UploadFileForm()
    return render(request,'admin/upload_tas_import.html', {
        'form': form, 
        'error': error,
        'section' : section
    })


# Public view of the page, also act as homepage
def public_view_list(request):
    courses = Course.objects.all()
    no_of_course = Course.objects.count()
    section = "home"

    return render(request, "course/public_view_list.html", {
        "courses" : courses,
        "has_courses" : no_of_course ,
        "section" : section,
    })


@user_passes_test(faculty_member_check, login_url='/accounts/login')
def faculty_view_list(request):
    courses = Course.objects.filter(faculties=request.user)
    no_of_course = courses.count()
    tas = User.objects.filter(is_ta=True)
    section = "faculty-home"

    if request.POST:
        form = SelectionForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()          
            messages.success(request, "TA information is updated.")
            return HttpResponseRedirect(request.get_full_path())
    else:
        form = SelectionForm(user=request.user)
    for course in courses:
        course.form_field = form[str(course.pk)]
    
    return render(request, "course/faculty_view_list.html", {
        "courses" : courses,
        "has_courses" : no_of_course,
        "section" : section,
    })

@user_passes_test(admin_member_check, login_url="/accounts/login")
def staff_add_course(request):
    title = "Add New Course"
    section = "course-home"

    if request.POST:
        course_form = CourseForm(request.POST)
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.save()
            course_form.save_m2m()
            messages.success(request, "New course is added!")

            return HttpResponseRedirect(reverse('staff-home-courses'))
    else:
        course_form = CourseForm()

    return render(request, 'admin/staff_add_course.html', {
        'course_form' : course_form,
        'title' : title,
        'section' : section,
    })

@user_passes_test(admin_member_check, login_url="/accounts/login")
def staff_edit_course(request, courseid):
    course = get_object_or_404(Course, pk=courseid)
    title = "Edit Existing Course"
    section = "course-home"

    if request.POST:
        course_form = CourseForm(request.POST, instance=course)
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.save()
            course_form.save_m2m()
            messages.success(request, "Course information is saved!")

            return HttpResponseRedirect(reverse('staff-home-courses'))
    else:
        course_form = CourseForm(instance=course)

    return render(request, 'admin/staff_add_course.html', {
        'course_form' : course_form,
        'title' : title,
        'section' : section,
    })

@user_passes_test(admin_member_check, login_url="/accounts/login")
def staff_delete_course(request, courseid):
    course = get_object_or_404(Course, pk=courseid)
    section = "course-home"

    if request.POST:
        course.delete()

        messages.success(request, "Course is deleted!")
        return HttpResponseRedirect(reverse('staff-home-courses'))

    return render(request, 'admin/staff_delete_dialog.html', {
        'course' : course,
        'section' : section,
    })

@user_passes_test(admin_member_check, login_url="/accounts/login")
def staff_delete_all_courses(request):
    courses = Course.objects.all()
    title = "Courses"
    redirect_url = '/admin/list_courses'
    target_url = '/admin/delete_all_courses'
    section = "course-home"

    if request.POST:
        courses.delete()

        messages.success(request, "All courses are deleted!")
        return HttpResponseRedirect(redirect_url)

    return render(request, 'admin/staff_delete_all_template.html', {
        "title" : title,
        "redirect_url" : redirect_url,
        "target_url" : target_url,
        "section" : section,
    })

def _request_csv_tas_upload(request, f):
    count = 0
    invalid_users = []
    reader = csv.reader(f.read().splitlines())
    next(reader, None) # skip the headers
    for r in reader:
        if len(r) != 1: raise ValueError 
        odin = r[0].strip()
        try:
            user_exists = User.objects.get(username=odin)
        except User.DoesNotExist:
            first_name, last_name = _get_ldap_user_data(odin)
            if first_name is not None:
                user = User()
                user.username = odin
                user.first_name = first_name
                user.last_name = last_name
                user.is_ta  = 1
                user.is_active = 1
                user.save()
                count = count + 1
            else:
                invalid_users.append(odin) 

    if count:
        messages.success(request, "CSV file is uploaded. %s new TAs are added!" % count)
    else:
        messages.warning(request, "TAs are already exist! No new TAs are created")

    if len(invalid_users) > 0:
        messages.warning(request, "There are some invalid Odin usernames: %s. Please correct it and submit the file again!" % ", ".join(map(str, invalid_users)))

def _request_csv_courses_upload(request, f):
    new_course = 0
    invalid_users = []
    
    reader = csv.reader(f.read().splitlines())
    next(reader, None) # skip the headers
    for r in reader:
        user = None
        course = None
        course_no, course_name, odin = [item.strip() for item in r] # IndexError or PackingError
        try:
            user = User.objects.get(username=odin)
        except User.DoesNotExist:
            first_name, last_name = _get_ldap_user_data(odin)
            if first_name is not None:
                user = User()
                user.username  = odin
                user.first_name = first_name
                user.last_name = last_name
                user.is_faculty = 1
                user.is_active = 1
            else:
                invalid_users.append(odin)

        try:
            course = Course.objects.get(course_no=course_no)
        except Course.DoesNotExist:
            course = Course()
            course.course_no = course_no
            course.course_name = course_name
            new_course = new_course + 1
        
        if user is not None and course is not None:
            user.save()
            course.save()
            course.faculties.add(user)
            course.save()

    if len(invalid_users) > 0:
        messages.warning(request, "There are some invalid Odin usernames: %s. Please correct it and submit the file again!" % ", ".join(map(str, invalid_users)))
    
    new_course = new_course - len(invalid_users)
    if new_course:
        messages.success(request, "CSV file is uploaded. %s new courses are added!" % new_course)
    else:
        messages.warning(request, "Courses uploaded are already exist! No new courses are created")

def _get_ldap_user_data(username):
    try:
        # Check if this username is an valid Odin username
        ld = ldap.initialize(settings.LDAP_URL)
        ld.simple_bind_s()
        results = ld.search_s(settings.LDAP_BASE_DN, ldap.SCOPE_SUBTREE, "uid=" + username)
        record = results[0][1]
    except IndexError:
        return None, None

    cn = record['cn']
    parts = cn[0].split(" ")
    first_name = parts[0]
    last_name = " ".join(parts[1:])

taassignment/views.py
from taassignment.courses.models import Course
from django.shortcuts import render, get_object_or_404

# Public view of the page, also act as homepage
def home(request):
    courses = Course.objects.all()
    no_of_course = Course.objects.count()
    section = "home"

    return render(request, "home.html", {
        "courses" : courses,
        "has_courses" : no_of_course ,
        "section" : section,
    })

taassignment/templates/courses/change_tas.html
{% extends "base.html" %}

{% block page_title %}TA Assignment{% endblock %}

{% block content %}

<!-- For Selector !-->
<script type="text/javascript" src="{{ STATIC_URL }}select2-3.4.6/select2.js"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}select2-3.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}select2-3.4.6/select2.css">
<script type="text/javascript">
$(document).ready(function() {
    $(".multi_select").each(function(){
        $(this).select2({
            placeholder: "Type in to select a TA",
            allowClear: true,
            maximumSelectionSize: $(this).data("max")
        });
    });
})
</script>

<h3 class="text-dark-green">Courses</h3>
<p>Your current classes are listed below. You may add/remove TAs from your class. Be sure to hit the save button when you are finished.</p>

{% if has_courses %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                {{ error }}
            {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Your current classes</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover" id="course-table">
                <thead class="text-dark-green">
                    <tr>
                        <th class="col-md-2">Course no.</th>
                        <th class="col-md-3">Course name</th>
                        <th class="col-md-3">Teacher</th>
                        <th class="col-md-4">TAs</th>
                    </tr>
                </thead>
                <tbody>
                    {% for course in courses %}
                    <tr>
                        <td class="col-md-2">{{ course.course_no }}</td>
                        <td class="col-md-3">{{ course.course_name }}</td>
                        <td class="col-md-3">{% for faculty in course.faculties.all %}
                                {{ faculty }}<br/>
                            {% endfor %}
                        </td>
                        <td class="col-md-4">
                            <div  class="form-group" style="margin-bottom: 0px">
                                {{ course.form_field }}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-4 col-md-2">
            <input type="submit" value="Save" class="btn btn-primary btn-block" tabindex="7">
        </div>
    </div>
</form>
{% else %}
<div class="alert alert-info">
    You have no classes currently!
</div>

    {% endif %}
{% endblock %}

taassignment/templates/courses/clear.html
{% extends "base.html" %}

{% block page_title %}Delete All {{ title }}{% endblock %}

{% block content %}
<h3 class="text-dark-green"> Delete All {{ title }} </h3>
<p>Click <b>Delete</b> button to delete all {{ title }} in the database.</p>  
<p class="alert alert-danger"><b>Notice:</b> It is impossible to recover the database after you did this action. <b>Please think twice!<b></p>
<div>
    <button class="btn btn-primary" data-toggle="modal" data-target="#delete_modal_all" title="Delete" >
        Delete
    </button>
    <a class="btn btn-default" href="{{ redirect_url }}">Cancel</a>
    <div class="modal fade" id="delete_modal_all" role="dialog">
        <div class="modal-dialog ">
            <form class="well delete-form" method="post" action="{{ target_url }}">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">×</button>
                  <h4 class="modal-title">Deleting {{ title }}</h4>
                </div>
                <div class="modal-body">
                     {% csrf_token %}
                     Are you sure that you want to delete <b>entire {{ title }}</b>?
                </div>
                <div class="modal-footer">
                     <button class="btn btn-primary" type="submit" value="Yes" >Yes</button>
                     <button class="btn btn-default"name="cancel"  data-dismiss="modal" value="No">No</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

taassignment/templates/courses/create.html
{% extends 'base.html' %}

{% block page_title %}TA Assignment Form - Admin Homepage{% endblock %}

{% block content %}

<script type="text/javascript" src="{{ STATIC_URL }}select2-3.4.6/select2.js"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}select2-3.4.6/select2-bootstrap.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}select2-3.4.6/select2.css">
<script type="text/javascript">
    $(document).ready(function() {
        $("#id_faculties").select2({
            placeholder: "Type in to select a teacher",
            allowClear: true
        });
        
        $("#id_tas").select2({
            placeholder: "Type in to select a TA",
            allowClear: true,
        });
    })
</script>

<form role="form" method="post" class="form-horizontal col-md-8" >
    {% csrf_token %}
    {% if course_form.errors %}
        <div class="alert alert-danger">
        {% for fields, errors in course_form.errors.items %}
            {% for error in errors %}
                {{ error }}
            {% endfor%}
        {% endfor %}
        </div>
    {% endif %}
    <h3 class="text-dark-green" >{{ title }}</h3>
    <p>Fill out the course information below:</p>
    <div class="row form-group">
        <label class="control-label col-md-2">{{ course_form.course_no.label }}</label>
        <div class="col-md-3">
            {{ course_form.course_no }}
        </div>
        <div class="col-md-6">
            {{ course_form.course_name }}
        </div>
    </div>
    <div class="row form-group">
        <label class="control-label col-md-2">{{ course_form.section_no.label }}</label>
        <div class="col-md-9">
            {{ course_form.section_no }}
        </div>
    </div>
    <div class="row form-group">
        <label class="control-label col-md-2">{{ course_form.faculties.label }}</label>
        <div class="col-md-9">
            {{ course_form.faculties }}
        </div>
    </div>
    <div class="row form-group">
        <label class="control-label col-md-2">{{ course_form.tas.label }}</label>
        <div class="col-md-3">
            <div id="max_tas">{{ course_form.max_tas }}</div>
        </div>
        <div class="col-md-6">
            {{ course_form.tas }}  
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2">
            <div class="col-md-4">
                <input type="submit" value="Save" class="btn btn-primary btn-block">
            </div>
            <div class="col-md-4">
                <a href="{% url 'courses-list' %}" class="btn btn-default btn-block">Cancel</a>
            </div>
        </div>
    </div>
    
</form>
{% endblock %}

taassignment/templates/courses/list.html
{% extends 'base.html' %}

{% block page_title %}Courses{% endblock %}

{% block content %}
<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/panel.js"></script>
<h3 class="text-dark-green">Course Management</h3>
<p>Here, you can add, edit or delete courses.</p>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Courses</h3>
        <div class="pull-right">
            <span class="clickable"><a href="{% url 'courses-download' %}">Download all Courses <i class="glyphicon glyphicon-download"></i></a></span>
            <span class="clickable"><a href="{% url 'courses-clear' %}">Clear all Courses <i class="glyphicon glyphicon-remove"></i></a></span>
            <span class="clickable"><a href="{% url 'courses-upload' %}">Import Courses <i class="glyphicon glyphicon-cloud-upload"></i></a></span>
            <span class="clickable"><a href="{% url 'courses-create' %}">Add Course</a><i class="glyphicon glyphicon-plus"></i>
            </span> 
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-hover" id="course-table">
            <thead class="text-dark-green">
                <tr>
                    <th class="col-md-2">Course number</th>
                    <th class="col-md-4">Course name</th>
                    <th class="col-md-3">Teacher</th>
                    <th class="col-md-3">Number of TAs Assigned</th>
                </tr>
                <tr id="search_box">
                    <td colspan="4">
                        <input type="text" class="form-control" id="course-table-filter" data-action="filter" data-filters="#course-table" placeholder="Filter Courses" />
                    </td>
                </tr>
            </thead>
            {% if courses.count %}
            <tbody>
                {% for course in courses %}
                <tr>
                    <td class="col-md-2">
                        <a data-toggle="modal" data-target="#delete_modal_course_{{ course.id }}" title="Delete" >
                            <i class="glyphicon glyphicon-remove"></i>
                        </a>
                        <div class="modal fade" id="delete_modal_course_{{ course.id }}" role="dialog">
                            <div class="modal-dialog ">
                                {% include 'courses/modal.html' %}
                            </div>
                        </div>
                        <a href="{% url 'courses-edit' course.id %}">{{ course }}</a></td>
                    <td class="col-md-4">{{ course.course_name }}</td>
                    <td class="col-md-3">
                        {% for faculty in course.faculties.all %}
                        <span>{{ faculty }}</span><br/>
                        {% endfor %}</td>
                    <td class="col-md-3">{{ course.tas.count }}/{{ course.max_tas }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">There are no classes!</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        
    </div>
</div>

{% endblock %}

taassignment/templates/courses/modal.html
<form class="well delete-form" method="post" action="{% url 'courses-delete' course.id %}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Deleting Course</h4>
    </div>
    <div class="modal-body">
        {% csrf_token %}
        Do you want to delete course
        <b>
            {{ course.course_name }}
        </b>?
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="submit" value="Yes" >Yes</button>
        <button class="btn btn-default"name="cancel"  data-dismiss="modal" value="No">No</button>
    </div>
</form>

taassignment/templates/courses/upload.html
{% extends "base.html" %}

{% block page_title %}Upload Courses{% endblock %}

{% block content %}
<h3 class="text-dark-green"> Upload Courses CSV File </h3>
<p>Upload a csv file containing five columns: course number, section number, course name, max number of TA's, and odin account of the faculty member teaching the class.</p>
<p><strong>Please use the <a href="{{ STATIC_URL }}csv_templates/course.csv" download="courses.csv">template file here</a>.</strong></p>
<form enctype="multipart/form-data" name="UploadCoursesImport" method="post" id="id_form_upload">
    {% csrf_token %}
    {% if error %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endif %}
    {{ form.file }}

    <br />
    <input type="submit" class="btn btn-primary" name="submit" value="Import" />
    <span class="btn btn-default">
        <a href="{% url 'courses-list' %}">Cancel</a>
    </span>
</form>
{% endblock %}